services:
  # PostgreSQL database (unchanged from original)
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: santaserver
      POSTGRES_PASSWORD: santaserver_dev
      POSTGRES_DB: santaserver
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U santaserver"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - santaserver-network

  # Unified SantaServer container (nginx + FastAPI + static assets)
  santaserver:
    build:
      context: .
      dockerfile: Dockerfile
    read_only: true
    tmpfs:
      - /tmp:size=100m,mode=1777
    environment:
      # Database connection
      - POSTGRES_SERVER=db
      - POSTGRES_USER=santaserver
      - POSTGRES_PASSWORD=santaserver_dev
      - POSTGRES_DB=santaserver
      - POSTGRES_PORT=5432
      
      # Application configuration
      - SECRET_KEY=development_secret_key_change_in_production
      - TENANT_ID=your_tenant_id
      - CLIENT_ID=your_client_id
      - CLIENT_SECRET=your_client_secret
      - ENVIRONMENT=development
      
      # Unified container specific configuration
      - UVICORN_UDS=/tmp/sockets/uvicorn.sock
      - NGINX_USER=nginx
      - SUPERVISOR_USER=nginx
      
      # CORS configuration (not needed but keeping for compatibility)
      - BACKEND_CORS_ORIGINS=http://localhost,http://localhost:8080,http://localhost:80
      
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      # Development volumes for hot reloading (can be removed in production)
      - ./backend:/app-dev/backend:ro
      - ./frontend:/app-dev/frontend:ro
      - ./config:/app-dev/config:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3
    restart: unless-stopped
    networks:
      - santaserver-network

volumes:
  postgres_data:
    driver: local

networks:
  santaserver-network:
    driver: bridge